#!/usr/bin/env python3
"""Deterministic SkillSentry report generator.

This is a light tool: no LLM calls, no network calls. It only reads existing
session/result artifacts and writes HTML reports.
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from sentry_diagnostics import collect_diagnostics, render_html_section
from sentry_gate import build_gate


GENERATED_REPORT_MARKERS = (
    "Generated by <code>sentry_ci.py</code>",
    "Generated by <code>sentry_publish.py</code>",
    "Generated by <code>sentry_report.py</code>",
    "<title>SkillSentry Publish Result</title>",
    "<title>SkillSentry CI Report</title>",
    "<title>SkillSentry CI Result</title>",
)


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def save_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def rate_text(rate) -> str:
    return "N/A" if rate is None else f"{rate:.1%}"


def delta_status(payload: dict) -> str:
    delta = payload.get("delta")
    if isinstance(delta, dict):
        return str(delta.get("status", "N/A"))
    if delta is None:
        return "N/A"
    return str(delta)


def should_replace_generated_report(report: Path) -> bool:
    """Return True when the path is missing or contains a generated fallback report."""
    if not report.exists():
        return True
    try:
        text = report.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return False
    return any(marker in text for marker in GENERATED_REPORT_MARKERS)


def render_base_style() -> str:
    return """
    body { font-family: system-ui, sans-serif; margin: 32px; line-height: 1.5; }
    code { background: #f4f4f4; padding: 2px 4px; }
    table { border-collapse: collapse; margin: 12px 0 20px; }
    th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }
    th { background: #f7f7f7; }
  """


def render_session_report(
    gate_result: dict,
    diagnostics: dict,
    *,
    title: str = "SkillSentry Report",
    generated_by: str = "sentry_report.py",
    footer: str | None = None,
) -> str:
    diagnostics_html = render_html_section(diagnostics)
    footer_text = footer or "Existing artifacts were read by the deterministic report tool."
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <title>{html.escape(title)}</title>
  <style>{render_base_style()}</style>
</head>
<body>
  <h1>{html.escape(title)}</h1>
  <p><strong>Verdict:</strong> {html.escape(str(gate_result.get("verdict", "UNKNOWN")))}</p>
  <p><strong>Grade:</strong> {html.escape(str(gate_result.get("grade", "N/A")))}</p>
  <p><strong>Authoritative pass rate:</strong> {rate_text(gate_result.get("authoritative_pass_rate"))}</p>
  <p><strong>Delta:</strong> {html.escape(delta_status(gate_result))}</p>
{diagnostics_html}
  <p>Generated by <code>{html.escape(generated_by)}</code>. {html.escape(footer_text)}</p>
</body>
</html>
"""


def write_session_report(
    session_dir: Path,
    gate_result: dict,
    *,
    output: Path | None = None,
    title: str = "SkillSentry Report",
    generated_by: str = "sentry_report.py",
    footer: str | None = None,
    diagnostics: dict | None = None,
) -> Path:
    report = output or (session_dir / "report.html")
    diagnostics_payload = diagnostics if diagnostics is not None else collect_diagnostics(session_dir, gate_result)
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(
        render_session_report(
            gate_result,
            diagnostics_payload,
            title=title,
            generated_by=generated_by,
            footer=footer,
        ),
        encoding="utf-8",
    )
    return report


def ensure_session_report(
    session_dir: Path,
    gate_result: dict,
    *,
    output: Path | None = None,
    title: str = "SkillSentry Report",
    generated_by: str = "sentry_report.py",
    footer: str | None = None,
    replace_generated_only: bool = True,
) -> Path:
    report = output or (session_dir / "report.html")
    if replace_generated_only and not should_replace_generated_report(report):
        return report
    return write_session_report(
        session_dir,
        gate_result,
        output=report,
        title=title,
        generated_by=generated_by,
        footer=footer,
    )


def render_ci_result_report(
    results: dict,
    *,
    skill: str,
    mode: str,
    generated_by: str = "sentry_report.py",
) -> str:
    summary = results.get("summary", {})
    if not isinstance(summary, dict):
        summary = {}
    diagnostics = results.get("diagnostics", {})
    if not isinstance(diagnostics, dict):
        diagnostics = {}
    reasons = "".join(f"<li>{html.escape(str(reason))}</li>" for reason in results.get("reasons", []))
    if not reasons:
        reasons = "<li>none</li>"
    diagnostics_html = render_html_section(diagnostics)
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <title>SkillSentry CI Result</title>
  <style>{render_base_style()}</style>
</head>
<body>
  <h1>SkillSentry CI Result</h1>
  <p><strong>Skill:</strong> {html.escape(str(skill))}</p>
  <p><strong>Mode:</strong> {html.escape(str(mode))}</p>
  <p><strong>Verdict:</strong> {html.escape(str(results.get("verdict", "UNKNOWN")))}</p>
  <p><strong>Grade:</strong> {html.escape(str(summary.get("grade", "N/A")))}</p>
  <p><strong>Authoritative pass rate:</strong> {rate_text(summary.get("authoritative_pass_rate"))}</p>
  <h2>Reasons</h2>
  <ul>{reasons}</ul>
{diagnostics_html}
  <p>Generated by <code>{html.escape(generated_by)}</code>.</p>
</body>
</html>
"""


def write_ci_result_report(
    report_path: Path,
    results: dict,
    *,
    skill: str,
    mode: str,
    generated_by: str = "sentry_report.py",
) -> Path:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        render_ci_result_report(results, skill=skill, mode=mode, generated_by=generated_by),
        encoding="utf-8",
    )
    return report_path


def ensure_ci_report_artifacts(
    output_dir: Path,
    results: dict,
    *,
    skill: str,
    mode: str,
    session_dir: Path | None = None,
    generated_by: str = "sentry_report.py",
) -> dict:
    """Ensure CI always exposes an HTML report artifact."""
    output_report = output_dir / "report.html"
    write_ci_result_report(output_report, results, skill=skill, mode=mode, generated_by=generated_by)
    artifacts = {"output_report_html": str(output_report)}

    if session_dir is not None:
        session_report = session_dir / "report.html"
        if not session_report.exists() or results.get("verdict") == "ERROR":
            write_ci_result_report(session_report, results, skill=skill, mode=mode, generated_by=generated_by)
        artifacts["session_report_html"] = str(session_report)

    return artifacts


def gate_for_session(session_dir: Path) -> dict:
    gate_file = session_dir / "gate-result.json"
    if gate_file.exists():
        return load_json(gate_file)
    gate = build_gate(session_dir)
    save_json(gate_file, gate)
    return gate


def results_from_eval_result(payload: dict) -> dict:
    return {
        "verdict": payload.get("verdict", "ERROR"),
        "reasons": payload.get("reasons", []),
        "summary": payload.get("summary", {}),
        "diagnostics": payload.get("diagnostics", {}),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate deterministic SkillSentry reports from existing artifacts.",
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--session-dir", help="Session directory containing gate/session artifacts")
    source.add_argument("--result", help="CI eval_result.json path")
    parser.add_argument("--output", help="Output HTML path. Defaults to session/report.html or result sibling report.html")
    parser.add_argument("--skill", default=None, help="Skill label for --result reports")
    parser.add_argument("--mode", default=None, help="Mode label for --result reports")
    parser.add_argument("--title", default="SkillSentry Report", help="Session report title")
    parser.add_argument("--force", action="store_true", help="Overwrite existing non-generated reports")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.session_dir:
        session_dir = Path(args.session_dir)
        output = Path(args.output) if args.output else None
        gate = gate_for_session(session_dir)
        report = ensure_session_report(
            session_dir,
            gate,
            output=output,
            title=args.title,
            generated_by="sentry_report.py",
            replace_generated_only=not args.force,
        )
    else:
        result_path = Path(args.result)
        payload = load_json(result_path)
        output = Path(args.output) if args.output else result_path.with_name("report.html")
        report = write_ci_result_report(
            output,
            results_from_eval_result(payload),
            skill=args.skill or payload.get("skill", "unknown"),
            mode=args.mode or payload.get("mode", "unknown"),
            generated_by="sentry_report.py",
        )
    print(json.dumps({"status": "OK", "step": "report", "report_html": str(report)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
